# Generated by Django 6.0.3 on 2026-03-17 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Age', models.PositiveBigIntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.PositiveBigIntegerField()),
            ],
        ),
    ]
