# Generated by Django 6.0.3 on 2026-03-17 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Projectsampleapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='Email',
            new_name='Email_id',
        ),
    ]
