# Generated by Django 6.0.3 on 2026-03-23 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projectsampleapp', '0002_rename_email_employee_email_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Age',
            field=models.PositiveIntegerField(),
        ),
    ]
