# Generated by Django 6.0.3 on 2026-03-23 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projectsampleapp', '0003_alter_employee_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Resume', models.FileField(upload_to='media')),
            ],
        ),
    ]
