# Generated by Django 6.0.3 on 2026-03-26 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projectsampleapp', '0005_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mark', models.IntegerField()),
                ('Grade', models.CharField(max_length=100)),
                ('Sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Projectsampleapp.student')),
            ],
        ),
    ]
